#!/usr/bin/env bash
# Generate default prompt - source this file before running the app

prompt_file=prompts/v1-gpt3
echo "Generating AGENT_PROMPT"
export AGENT_PROMPT="$(awk 'BEGIN{}{out=out$0"\n"}END{print out}' $prompt_file| sed 's/\n$//')"
